name: Chloekingart
favicon: null
layout_spectrum: 0.2065212968736887
typography_spectrum: 0.8768548944499344
title: My Dank Art
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6702623381279409
  lightness: 0.8610307974740863
  saturation: 0.6592396907508373
  rhythmicContrast: 0.26697066193446517
purpose: []
